language: php

dist: bionic

before_script:
  - composer install

php:
  - 7.4

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "statscore"
    token:
      secure: "Tr+uz8es3d4FXLZRUZVY2lsiSY0PWxazTFCgYGT4rDZqiushuM3lj/xOB8fVaDtGuhzWyO11k7fRvHHYvoE64ZQmy1ORdPcZ1kpAb2FGnIt1WbyMh8ArlcNXj6APS7LhpDp+/LAXR29zQ0KcZyKKdm+swTrZGzcJDvxchSyTBQptVMvh2f8oOjUWVypTAun2Dlomh3/xxCWhsvTFCNaXYGi/wClXax7Yy2H5Ip0ZWJa4PtL4RCItp5YOpqbec0tOsTH5Yez8YvusCSiqTZQhx6ZxSamSDZlRtJBVVHtn+QsF8uox2sfwRwlVXaFBkqI5Ogio5qM0mhd5+fiL/W9xAc/w/Fg/Bx6NwNMvbQwugfZtcchQdNOvyrFvzSAHVOAXfUL7EMQb2gOMKYAI05q5JLIPzNfB0pYE+3CunVIIjk6Hm4H9ZXsryKkYOC0862n9OibiMN+0QHh2+tLdAWiRRPkuaWZyD1ph2VtlKAqwf+wnr1suVXqbW91p/Ng0Ag32P1mb7yF1Y0PWwldNOqrg1TuUSFJ/MSxSOL9rAAimFkHLKuWijN0TVd+xtqgANIlm6WzjYJMOOxJ+aE7/XwsxfUcdHbcLhnSqnyCyLwZ3Z6/fUuMKaiaIoTO9Touq53rvVubYvgDCoElm2BXD9Sd87H/EGLMK3Dj15Ntx9CYVUtQ="

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test-report.xml
  - sonar-scanner