language: php
dist: bionic
before_script:
  - composer install
php:
  - 7.4
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: statscore
    token:
      secure: kbhNOo8CCj+bOI6MvtGRqcV9xc3+2xg+ADB3r0xvzfr7Hff1sfpM1bk+6F/HdMHqwnR6Y/1b5qJS1lBBSGoXraXxNLJntaNXTKdHX21N2YY3iSPd3cHo/uf3YUZlPNHiT5+s0lj0JVX+5ZPBortw21difxX9eM2P5CqrTUfZAtVQE4wUzYqrWbLpURv9RKApn0TOVdn4rmgwacx6SMmYPgxtjzvj18Zq44Z/xjDaaW8dOUYyL6VukQZC5zy2wUgA41lDpTmxBZK6DJdwOR7Lv8dL/FYueMO80/zdfw3KXbs/Aef0hjjYSgX06aPulzicg30NKrtX0lbLcgD5pun5whf8KUmMSBRpzm23MiUbvQheVDX2bN6cUUmaUboTO4YnKJ8CfvQGcuHFzfHaghuq/xb1zuimBUO9klzc1AVdfrDCOPv+DBZ9xpsHdJXDhskhHfbJmAr1MSrKjysTIA9LXPOk2H7yeLQYiRZ9UUAtcvhL44jH6kx/TWwFb0jyM/Gsf0YuLVKwNyM5neP3SG14GRDBY9Nji7fjXdRzp7dbn8hGaVOxHMzAnsG5nGIJaI9WZ1P/dekNSfCWtxTulIPcqrPcSQuGtRwNpLZBIEYONMpiZLtpJsZ/IaK3eAnUJSaBrANWdvUMxSGFCYgEYQAiYhF+UolbT7Y6rwmXQB/HX/8=
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test-report.xml
  - sonar-scanner
env:
  global:
    secure: kty0wAHbrNH4CoA6J3ciVqYGNLMq+EvirTJozpi39lg8tAz2nptG0b6NgBDTeZh31dD7zAiJBLR0jKYFmN67jRXiB/5rS99MZ9wiq3RFQ7asYIbl9HmTwnvyefU9MqAD3u7b8Q8MYQuMGUUJBn1B0Hx2nCZafQnO7YGbgHfhDkZqRxETC+91muJ9T8BDwqM3JcQrvWCdcmmg7OTcGHDePhbBBR/Ezj44saVbPqHOEhkwKQPIlzRbA9Se01rocfGygrmCP/HybTIi43IdSFrOC0V5Ft90hH1PLM7yvRzbz/a3UjS3pUUf6k1Ky5ZG9fTLXlVcXyO/UIgQRg2liy3gebVJyTdeOWyOgSDVg0Zgaa2YFJHr9zs01j32pOCjv15VHxNQaMV0KUNaIwjOXYfixUnzoYdJppYYLoPdAPvyS10XPdGZt6jl5/mhFyeFeZheJQqW55W1rImqaZf2raq3uQjzajqCRhu7pKpczE4JWYGiieNirnb6W2gKQ613THvmmMH5YTSNB4OVqg9jVCsI2RSBduugem6uZu+EYs8uTYzcXROUC9cIAhWPiyBJzffA5ssM2TKuCmhzSD3vtaXtOeOdh7Pq8PGqNcPuHxbl9DkExNhmXJR90rIrjqHTR3Mo8WKQd9oIy1zza7AFFRmLvsevJmaZRTS9U51rEBGSbiY=
